name: Auto Update IPTV
on:
  schedule:
    - cron: '0 */6 * * *' # يعمل كل 6 ساعات
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-level: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run Update Script
        run: python update_links.py
      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add playlist.m3u
          git commit -m "Auto-update IPTV link" || exit 0
          git push
